server:
  port: 21210
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RubyCong/Microservice.git
          #git不支持searchPath操作，本地可以
          #searchPaths: data
  rabbitmq:
    host: localhost
    port: 5672 
management:
  security:
    enabled: false